// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdminController from "./admin_controller"
application.register("admin", AdminController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProfessorController from "./professor_controller"
application.register("professor", ProfessorController)

import StudentController from "./student_controller"
application.register("student", StudentController)
